content:
  - name: prompt-engineering
    label: Guides
    path: env/content/prompt-engineering
    type: collection

  - name: team
    label: Team
    path: env/content/team
    format: yaml-frontmatter
    type: collection
    fields: 
      - name: department
        type: select
        options:
          values: [founders]
      - name: image
        label: Headshot
        type: image
      - name: action
        label: Action Image
        type: image
      - name: weight
        type: number
    

media: env/assets/images
