content:
  - name: prompt-engineering
    label: Guides
    path: env/content/prompt-engineering
    type: collection

  - name: team
    label: Team
    path: env/content/team
    format: yaml-frontmatter
    type: collection
    fields: 
      - name: Headshot
        type: image
      - name: Action Image
        type: image
    

media: env/assets/images
